### ISSUE TITLE
AttributeError: 'sage.rings.integer.Integer' object has no attribute 'hex'

### ISSUE THREAD

**Issue by aulnes** [daira/pluto-eris#1]
when running run.sh，I met this problem:

Traceback (most recent call last):
  File "verify.sage.py", line 453, in <module>
    verify()
  File "verify.sage.py", line 68, in verify
    verify_pass(V, needtofactor)
  File "verify.sage.py", line 175, in verify_pass
    writefile('hex-p',p.hex() + '\n')
  File "sage/structure/element.pyx", line 484, in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4303)
  File "sage/structure/element.pyx", line 497, in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4412)
  File "sage/cpython/getattr.pyx", line 254, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:1834)
AttributeError: 'sage.rings.integer.Integer' object has no attribute 'hex'
Traceback (most recent call last):
  File "verify.sage.py", line 453, in <module>
    verify()
  File "verify.sage.py", line 68, in verify
    verify_pass(V, needtofactor)
  File "verify.sage.py", line 175, in verify_pass
    writefile('hex-p',p.hex() + '\n')
  File "sage/structure/element.pyx", line 484, in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4303)
  File "sage/structure/element.pyx", line 497, in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4412)
  File "sage/cpython/getattr.pyx", line 254, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:1834)
AttributeError: 'sage.rings.integer.Integer' object has no attribute 'hex'

Ep (Pluto)
----------
Ep/verify-lisprime = Unverified
Ep/verify-pisprime = Unverified

Eq (Eris)
---------
Eq/verify-lisprime = Unverified
Eq/verify-pisprime = Unverified

ENVIRONMENT:
---------
ubuntu 18.04 LTS, SAGEMATH 8.1

**Comment by aulnes** [comment]
I wonder if this is caused by the low version of sagemath
